feat/add-axlusdc-alt-pool-balance
platypus-finance/DefiLlama-Adapters pull request #11
Opened 2022-12-13 02:04 UTC by hannosuke16

**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

##### Twitter Link:

##### List of audit links if any:

##### Website Link:

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

##### Current TVL:

##### Chain:

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

##### Short Description (to be shown on DefiLlama):

##### Token address and ticker if any:

##### Category (full list at https://defillama.com/categories) *Please choose only one:

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

##### forkedFrom (Does your project originate from another project):

##### methodology (what is being counted as tvl, how is tvl being calculated):

2022-12-13 02:04 UTC, llamatester commented
The adapter at projects/platypus-finance exports TVL: 
        
 
 
    avax-staking              1.75 M
    avax                      35.47 M
    staking                   1.75 M
    
    total                    35.47 M

2022-12-14 12:16 UTC, devisfun201 commented on projects/platypus-finance/constants.js
> +  AXLUSDC: {
need to add `ALT_USDC_AXLUSDC_LP` under `USDC` as well.

2022-12-14 12:17 UTC, devisfun201 requested changes
need to add ALT_USDC_AXLUSDC_LP under USDC as well.

2022-12-15 02:43 UTC, llamatester commented
The adapter at projects/platypus-finance exports TVL: 
        
 
 
    avax-staking              1.86 M
    avax                      36.46 M
    staking                   1.86 M
    
    total                    36.46 M

2022-12-15 02:59 UTC, shinji2 approved these changes

2022-12-15 03:03 UTC, devisfun201 approved these changes

2022-12-15 04:09 UTC, merged